### PR TITLE
[elasticsearch][kibana] Add flexible ingress

### LINKED ISSUE #979: elasticsearch multiple ingress rules.
Would be nice for the elasticsearch ingress.yaml to support multiple host/path rules like logstash ingress.yaml.

### PR DESCRIPTION
**Pull request by kevinsmithwrs**
- [x] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [x] README.md updated with any new values or changes
- [x] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

Fix #979

### CODE REVIEW

**Comment by jmlrt** [comment]
cla/check

**Comment by jmlrt** [comment]
jenkins test this please

**Review by jmlrt — CHANGES_REQUESTED** [review]

**Comment by jmlrt** [comment]
jenkins test this please

**Review by jmlrt — APPROVED** [review]
LGTM but we need to keep backward compatibility => added in ae0d1688

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by yurrriq** [comment]
> LGTM but we need to keep backward compatibility

With no changes to our values, this change broke our Helm release. Is it the case that this chart does not follow semantic versioning? I would have expected a major version bump for this breaking change.

**Comment by jmlrt** [comment]
Hi @yurrriq,
This change has been updated to ensure backward compatibility. 
It shouldn't have any impacts on existing release, that's why we removed the `breaking change` label.
If you had some issue with this change and your existing values, it's a bug.
Can you open a new ticket and provides all details required so we can investigate?

**Comment by yurrriq** [comment]
> This change has been updated to ensure backward compatibility.

Unfortunately, that is not the case. The breaking change is [here](https://github.com/elastic/helm-charts/pull/994/files#diff-e1b653a6ed8aa2237ff5a81d6cba9bdc38a0e7a11ddfa28f739a62368f51ed9c
), where the schema for `ingress.hosts` was changed dramatically.

**Comment by yurrriq** [comment]
I have created https://github.com/elastic/helm-charts/issues/1090

**Pull request merged**
