### PR TITLE
remove cluster.deprecation_indexing.enabled env when disabled

### LINKED ISSUE #1492: Make "cluster.deprecation_indexing.enabled" optional
**Chart version:** 7.16.1 (with Elasticsearch-Image 7.6.2)

**Kubernetes version:** 1.19.x

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine) Bare-Metal

**Helm Version:** 3.6.3

**`helm get release` output**
not relevant

**Describe the bug:**
The new helm-chart version introduced this new environment variable which is of course not supported by our underlying ES version (ES crashes then). We want to do this chart-update to get the new v1-Ingress in-place to do subsequent infrastructure updates.

**Steps to reproduce:**

1. Install the newest chart version with an older ES image version
2. ES won't start

**Expected behavior:**
The "cluster.deprecation_indexing.enabled" parameter should be made optional.

**Provide logs and/or server output (if relevant):**

*Be careful to obfuscate every secrets (credentials, token, public IP, ...) that could be visible in the output before copy-pasting*

```
```

**Any additional context:**

### PR DESCRIPTION
**Pull request by ckotzbauer**
fix #1492

- [x] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [x] README.md updated with any new values or changes
- [x] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

### CODE REVIEW

**Comment by ckotzbauer** [comment]
I signed the CLA right after opening this PR.

**Comment by ckotzbauer** [comment]
@jmlrt Sorry for pinging you directly, but is it possible to review and merge this PR in the next few days that it is included in the next released chart version which is hopefully not so far away?
The existance of this environment variable blocks us from updating the chart to 7.16.x which is the first version with Ingress v1 included. This is mandatory for upcoming updates to our infrastructure...

**Comment by ckotzbauer** [comment]
Closing community-PRs without reason is not really the best thing ...
Is there any reason why this is closed? The linked issue is still present and blocks people.

**Comment by jmlrt** [comment]
Hi @ckotzbauer, this PR was automatically closed because I removed the `7.x` branch, the PR should target the `main` branch as mentionned in the [contributing guide](https://github.com/elastic/helm-charts/blob/main/CONTRIBUTING.md#submitting-a-pull-request).

As for the content of the PR, I'll answer directly on the issue ticket.

**Pull request closed without merging**
