### PR TITLE
[elasticsearch] fix escaping issue in readinessprobe (#625)

### PR DESCRIPTION
**Pull request by denysvitali**
- [X] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [X] README.md updated with any new values or changes
- [ ] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

### CODE REVIEW

**Comment by denysvitali** [comment]
CLA signed, but the CLA bot doesn't seem to mark it as signed. Let's wait...

**Comment by denysvitali** [comment]
Nevermind, this implementation needs to be double checked: it fails if the username/password is not set :thinking:

**Comment by fatmcgav** [comment]
@denysvitali Cheers for taking the time to open the issue and this PR.

I think your implementation is pretty much there. 
However I've been doing some refactoring of the `readinessProbe` in-order to resolve #631, which should also solve this issue.
Feel free to test the changes in #638 and let me know if they work for you.

**Comment by denysvitali** [comment]
Thanks @fatmcgav !
I'll make sure to check your changes, thanks for fixing the issue!

**Comment by fatmcgav** [comment]
Superseded by #638

**Pull request closed without merging**
