### PR TITLE
[elasticsearch] Adds imagePullSecrets for test Pod

### PR DESCRIPTION
**Pull request by marcostvz**
- [x] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [ ] README.md updated with any new values or changes
- [ ] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

### CODE REVIEW

**Comment by marcostvz** [comment]
Signed

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by jmlrt** [comment]
Hi @marcostvz, thank you for this PR. Can you sign the CLA?

**Comment by marcostvz** [comment]
I had to re-sign the commit, thanks for your quick review @jmlrt

**Comment by jmlrt** [comment]
jenkins test this please

**Pull request merged**
