### PR TITLE
add possibility to control automount service account token

### PR DESCRIPTION
**Pull request by rccrdpccl**
- [x] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [x] README.md updated with any new values or changes
- [ ] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

### CODE REVIEW

**Comment by rccrdpccl** [comment]
Fixes #501

**Comment by rccrdpccl** [comment]
Are tests template and integration tests for this feature? @jmlrt

**Comment by rccrdpccl** [comment]
Is there any interest in merging this @jmlrt ? It's not a big change, but the more it sits here the more conflicts it will have.

**Comment by jmlrt** [comment]
Hey @rccrdpccl,
Thank you for this PR. You did well pinging me.

At first sight this PR looks fine and we should be able to merge it if you can merge master to your branch and fix the conflicts.

**Pull request closed without merging**
