### PR TITLE
7.13

### PR DESCRIPTION
**Pull request by drenze-athene**
APM Server labels are applied at the deployment level only, not at the pod level. This does not align with the behavior of other Elastic helm charts in this collection. Additionally, it creates issues when using tools, which require specific labels to be applied to pods (i.e., validation tools, such as [OPA Gatekeeper](https://github.com/open-policy-agent/gatekeeper)).

Add labels defined under the `labels: {}` tag in `values.yml` to correct this issue.

- [x] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [x] README.md updated with any new values or changes
- [x] Updated template tests in `${CHART}/tests/*.py` 
- [x] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

### CODE REVIEW

**Comment by jmlrt** [comment]
Hi @drenze-athene, can you be a bit more explicit about what this PR is for?

**Comment by drenze-athene** [comment]
> Hi @drenze-athene, can you be a bit more explicit about what this PR is for?

Apologies. I had the notes in the commit, neglected to copy them over to the PR. I've edited the PR comments to include an explanation of the commit.

**Review by jmlrt — COMMENTED** [review]
Changes looks fine, however PR should target master branch with backport PR handled by Elastic maintainer. Can you reopen it to master branch?

**Comment by drenze-athene** [comment]
You bet.

**Comment by drenze-athene** [comment]
Closing, and reopening PR to master per request from @jmlrt

**Pull request closed without merging**
