### PR TITLE
small typo: parralel->parallel

### PR DESCRIPTION
**Pull request by kcm**

### CODE REVIEW

**Comment by jordansissel** [comment]
@Crazybus The kibana security test failed, but this PR doesn't touch that. Thoughts?

**Comment by kcm** [comment]
Looks like a transient CI issue:

```
14:59:04 https://localhost:5601/app/kibana: status: Error: Get https://localhost:5601/app/kibana: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

**Comment by Crazybus** [comment]
> @Crazybus The kibana security test failed, but this PR doesn't touch that. Thoughts?

Does indeed look transient. I haven't seen this being flakey before but it is certainly unrelated to this change. 

@kcm Can you rebase on master? There is now a merge conflict.

**Comment by Crazybus** [comment]
> I haven't seen this being flakey before but it is certainly unrelated to this change.

I saw the same thing in my PR so I have added some extra retries to improve the stability in #75

**Comment by kcm** [comment]
Just going to open a new one since it'll be way easier than doing a local fork, rebase, resolution, and transmogifrication.

**Pull request closed without merging**
