### PR TITLE
895

### PR DESCRIPTION
**Pull request by ryan-dyer-sp**
- [x] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [x] README.md updated with any new values or changes
- [x] Updated template tests in `${CHART}/tests/*.py` 
- [no] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

Did not add any integration tests for this as I'm not sure how goss runs.  If it runs by attempting to actually create a k8s object then this would likely fail unless the cluster in question has the servicemonitor crd.

Fixes Issue #895

### CODE REVIEW

**Comment by ryan-dyer-sp** [comment]
CLA has been signed.

**Comment by jmlrt** [comment]
Hi @vinothayyavoo, thank you for this feature request.
`ServiceMonitor` isn't a Kubernetes standard but is specific to Prometheus.
We may revisit it later, but want to avoid managing integration with third party resources outside of Elastic products and Kubernetes standard resources in Elastic charts currently.

**Comment by ryan-dyer-sp** [comment]
@jmlrt I assume you meant me.

What about the headless service part?  Every piece that can be added to support the usecase makes it easier for users to monitor filebeats.

And though I can understand the opinion, its not one that is shared among many helm charts.  The majority of people running kubernetes, also run prometheus and want a way to scrape metrics.  Filebeats doesnt support an openmetrics standard (even though there's been a ticket open for a long time asking for this) and the extraContainers aspect of the helm chart is sufficient for adding this functionality.  Would you support a generic extraManifests value?  Where it could be an array of manifests that get added?  That way we could add whatever additional objects were needed to make filebeat fully integrate into our environments?

**Comment by jmlrt** [comment]
Hi @ryan-dyer-sp,
First I'm sorry for the name mistake.

I'm not sure to get the point about headless service.

Elastic recommands using our Metricbeat chart to get pods metrics and inject them into Elasticsearch, that's another reason if needed why we won't add Prometheus integration into our charts.

Adding some `extraManifest` or `extraYaml` value has been discussed in a similar issue in https://github.com/elastic/helm-charts/issues/231#issuecomment-514235426. It's something that we could merge if you're interested in submitting a PR.

**Comment by ryan-dyer-sp** [comment]
@jmlrt The metrics being available in elasticsearch isnt of any use to us at this time, we want them in prometheus.  

For a servicemonitor to work you need a headless service in order for prometheus to determine the various pod IPs (via the endpoints) to scrape.  The argument was elastic doesnt want to support non-native k8s objects.  A headless service is a native k8s construct.  So would you prefer to keep the headless service creation (and change the field to be .Values.service.enabled)  or do you prefer to keep it all out of the helm chart entirely and just allow users to do it via an extraManifests if they need it?

I will modify the PR to add an extraManifest field as a way to inject additional manifests into the helm chart, thanks!

**Pull request closed without merging**
