### PR TITLE
[metricbeat] Add missing labels for deployment

### PR DESCRIPTION
**Pull request by vliubko**
Earlier, `.Values.labels` were propagated for the **daemonset** only.
https://github.com/elastic/helm-charts/blob/master/metricbeat/templates/daemonset.yaml#L44

This PR will resolve this and add these labels for the **deployment** too.

### CODE REVIEW

**Comment by vliubko** [comment]
Hi, guys ^__^
@jmlrt @fatmcgav

**Review by jmlrt — APPROVED** [review]
LGTM⛴

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by jmlrt** [comment]
backported to `6.8`, `7.9` and `7.x` branches

**Pull request merged**
