### PR TITLE
[meta] stabilize CI tests

### PR DESCRIPTION
**Pull request by jmlrt**
This PR add some improvements to stabilize CI tests which are flaking at this time:

- watch resources rollout after upgrade to ensure that goss tests when rollout is done
- use newest running pod for goss tests to ensure that it is not using a pod from previous release or a pod which is terminating
- remove mention of hostname in goss tests to ensure that test can run in every pods of the Statefulsets, DaemonSets or Deployments
- increase some more timeouts for Elasticsearch tests
- standardize examples to simplify maintenance and diff

### CODE REVIEW

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by jmlrt** [comment]
CI test is 🟢 again 🎉

**Review by Conky5 — APPROVED** [review]
LGTM! :100:

**Pull request merged**
