### PR TITLE
[metricbeat] Enable events access to cluster role

### PR DESCRIPTION
**Pull request by Azuka**
Metricbeat apparently needs access to events. I had to manually make this change to the clusterrole when installing the chart due to the following error:

`Performing a resource sync err kubernetes api: Failure 403 events is forbidden: User "system:serviceaccount:monitoring:metricbeat-metricbeat" cannot list resource "events" in API group "" at the cluster scope for *v1.EventList`

I haven't tried `filebeat` yet so I'm not sure this change is also required for it.

- [x] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [ ] README.md updated with any new values or changes
- [ ] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

### CODE REVIEW

**Comment by Azuka** [comment]
@Crazybus do you mind taking a look at this?

**Comment by chendo** [comment]
On chart version v7.3.0, I used applied the `clusterrole` defined at https://github.com/elastic/beats/blob/master/deploy/kubernetes/metricbeat-kubernetes.yaml#L312-L340 and it solved my issues, which primarily manifested as no CPU or memory data being visible in the Infrastructure tab on Kibana.

However, I'm still unable to Group By: Namespace

**Comment by Crazybus** [comment]
jenkins test this please

**Comment by Crazybus** [comment]
jenkins test this please

**Comment by Crazybus** [comment]
Thanks for fixing this one up! And sorry for the slow review (I was on vacation).

**Pull request merged**
