### PR TITLE
[elasticsearch] Add volumeClaimTemplate.storageClassName

### PR DESCRIPTION
**Pull request by RammusXu**
default to ssd

- [x] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [ ] README.md updated with any new values or changes
- [ ] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

### CODE REVIEW

**Comment by jmlrt** [comment]
cla/check

**Review by jmlrt — CHANGES_REQUESTED** [review]
Hi @RammusXu, can you be a bit more explicit about why we should add this commented value? 

Also signing the CLA is required for PR: https://www.elastic.co/contributor-agreement

**Comment by RammusXu** [comment]
> Hi @RammusXu, can you be a bit more explicit about why we should add this commented value?

When I try to deploy this to alibabacloud hosted kubernetes, it fails. I need to specify the `storageClassName` to make it run. 
Thus, I think `storageClassName: ssd` will be helpful.

Also, I can see it as default values anywhere, like https://github.com/bitnami/charts/blob/master/bitnami/redis-cluster/values.yaml#L705-L708

> Also signing the CLA is required for PR: https://www.elastic.co/contributor-agreement

I have signed it and now I can see the CLA check is green. Is it ok?

**Comment by jmlrt** [comment]
still valid

**Pull request closed without merging**
