### PR TITLE
Fix typo in FAQ

### PR DESCRIPTION
**Pull request by SlavaSubotskiy**
- [ ] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [ ] README.md updated with any new values or changes
- [ ] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

### CODE REVIEW

**Comment by jmlrt** [comment]
cla/check

**Comment by SlavaSubotskiy** [comment]
Dear @jmlrt, thank you for review!
Your comment is valid for 'metricbeat', but the proposed fix is for 'filebeat' chart.
In the case of 'filebeat' chart '.Values.hostNetworking' is used: https://github.com/elastic/helm-charts/blob/master/filebeat/templates/daemonset.yaml#L55

**Comment by jmlrt** [comment]
Ooops, sorry for my mistake... Reopenning

**Review by jmlrt — APPROVED** [review]
LGTM⛴

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by jmlrt** [comment]
backported to `6.8`, `7.9` and `7.x` branches

**Pull request merged**
