### PR TITLE
[kibana] optionally disable SA token automount

### PR DESCRIPTION
**Pull request by jonkerj**
### Benefits
By disabling the automount, potential attackers cannot access the Kubernetes API on behalf/through the pod.

### Possible drawbacks
If anyone is using some sidecar or plugin to access the Kubernetes API, they will have to explicitly enable (`--set automountToken=true`) the automount of the SA token in the values.

### Applicable issues
#1330 

- [x] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [x] README.md updated with any new values or changes
- [x] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

### CODE REVIEW

**Comment by jonkerj** [comment]
Hi devs, is there anything I can do to get this ball rolling?

**Comment by jonkerj** [comment]
@jmlrt any chance you could take a look at this PR? Looks like you are an active dev here, and I'd really like this feature at least considered 😉

**Review by jmlrt — CHANGES_REQUESTED** [review]
Hi @jonkerj, sorry for the late answer.
This PR makes sense, however I have a few comments:

- unless cases where a change is only valid for a specific version, PR should be opened to master branch then Elastic handle the backport to the other branches
- the default value should be True to avoid a breaking change

Also I don't know if we should migrate the way we configure service accounts to be like elasticsearch chart with a rbac value before this change. I would to think about it.

**Comment by jonkerj** [comment]
Hi there, same here: I've (re)signed the CLA, rebased and changed the default. Should be good now

**Review by jmlrt — APPROVED** [review]
LGTM⛴

**Comment by jmlrt** [comment]
jenkins test this please

**Review by jmlrt — CHANGES_REQUESTED** [review]
Some changes are required to make [Black](https://black.readthedocs.io/en/stable/) formatter happy in [elastic+helm-charts+pull-request+lint-python/1092](https://devops-ci.elastic.co/job/elastic+helm-charts+pull-request+lint-python/1092/label=docker&&virtual&&ubuntu-18.04/console).

Can you run `black kibana/tests/kibana_test.py`?

**Comment by jonkerj** [comment]
done

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by jonkerj** [comment]
@jmlrt : is there anything else I can do?

**Comment by jmlrt** [comment]
Hi @jonkerj, sorry the PR is approved but CI tests are broken for now.
I'll admin-merge it because I don't have time to fix the jobs for now.

**Pull request merged**
