### PR TITLE
[apm-server] run as non root user

### LINKED ISSUE #785: apm-server: Run as non-root user
**Describe the feature:**
I want to run apm-server as a non-root user, same as described here: https://github.com/helm/charts/pull/18366

Currently, if I set `podSecurityContext`, the Pod fails with the error:
 ```
Exiting: error loading config file: open apm-server.yml: permission denied
```

### PR DESCRIPTION
**Pull request by jmlrt**
This commit update APM server pod to run with UID 1000 instead of 0 (root).

Note that GID 0 is still required due to apm-server binary default files
permissions.

Fix #785

### CODE REVIEW

**Comment by Conky5** [comment]
It looks like all the apm-server tests had an issue.

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by jmlrt** [comment]
unrelated transient issue, @Conky5 PTAL

**Review by Conky5 — APPROVED** [review]
LGTM

**Comment by jmlrt** [comment]
jenkins test this please

**Pull request merged**
