### PR TITLE
Adding namespace metadata to resources

### LINKED ISSUE #1438: Add namespace to resource metadata
**Describe the feature:**
It would be nice to have the namespace variable in all appropriate resources metadata, so that it is there when rendering out templates  to disk for use by other tools

will submit a pull request for this shortly

**Describe a specific use case for the feature:**

### PR DESCRIPTION
**Pull request by barrymars**
Fixes #1438 

- [ ] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [ ] README.md updated with any new values or changes
- [ ] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

### CODE REVIEW

**Comment by krystian-kulgawczuk** [comment]
@barrymars Do you intend to continue working on this issue?

**Comment by barrymars** [comment]
@krystian-kulgawczuk what else needs doing to it?

**Comment by krystian-kulgawczuk** [comment]
@barrymars Nevermind. I thought that you abandoned this issue as the contribution agreement was not signed. Let's wait for someone from the organization.

**Comment by barrymars** [comment]
sorry about that, I had done it earlier but it didn't register, so just did it again

**Comment by krystian-kulgawczuk** [comment]
No problems :) Either way, we'll wait a little while for it to be looked at by someone who can merge it.

**Comment by framsouza** [comment]
jenkins test this please

**Review by framsouza — COMMENTED** [review]
Can you please add the namespace also on the README.md for each resource, as we describe [here](https://github.com/elastic/helm-charts/blob/main/CONTRIBUTING.md#requirements-for-submiting-a-pull-request).

Make sure to also add the proper python test for the namespace utilisation, (e.g https://github.com/elastic/helm-charts/blob/c52ad079379e6b1ba420866cdf96019f382f94ff/elasticsearch/tests/elasticsearch_test.py#L220).

Make sure to follow all the requirements I linked above.

**Pull request closed without merging**
