### PR TITLE
add logic to probes

### PR DESCRIPTION
**Pull request by moosecanswim**
- [x] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [x] README.md updated with any new values or changes
- [ ] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

### CODE REVIEW

**Comment by moosecanswim** [comment]
I've signed the cla already

**Comment by jmlrt** [comment]
Hi @moosecanswim, we expect to have probes with default configuration, can you explain what would be the reason to remove them?

**Comment by jmlrt** [comment]
Hi @moosecanswim, thank you for this PR and sorry for the delays.
We always want to have readiness and liveness probes in default values.
If you want to be able to override or disable a probe, you can use the following yaml syntax:

```yaml
# disable livenessProbe
livenessProbe: null

# replace httpGet default readinessProbe by some exec probe
readinessProbe:
  httpGet: null
  exec:
    command:
      - curl
      - localhost:9600
```

**Comment by moosecanswim** [comment]
thanks @jmlrt ill give that a try.

**Pull request closed without merging**
