### PR TITLE
Add deployment annotations

### PR DESCRIPTION
**Pull request by clyfish**
- [x] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [x] README.md updated with any new values or changes
- [x] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

### CODE REVIEW

**Comment by clyfish** [comment]
I've signed the agreement.

**Comment by fatmcgav** [comment]
Jenkins test this please

**Comment by fatmcgav** [comment]
@clyfish Tests all look good.

However it looks like there's now a merge conflict. Would you mind merging `master` and updating the PR?

**Comment by clyfish** [comment]
@fatmcgav done

**Comment by fatmcgav** [comment]
Thanks @clyfish 

Jenkins test this please

**Pull request closed without merging**
