### PR TITLE
[kibana] Add posibility to re-define http code for health-check

### PR DESCRIPTION
**Pull request by SergK**
When using plugins which enable SSO for kibana http code is changed
from 200 to 301 since "healthCheckPath" is now under "protection".
This patch introduce new value: healthCheckHttpCode which can be
changed depending on deployment schema

Signed-off-by: Sergiy Kulanov <sergey@kulanov.org.ua>

- [*] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [*] README.md updated with any new values or changes
- [*] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

### CODE REVIEW

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by SergK** [comment]
Hi @jmlrt, any chance to make this available in the next release? Thank you

**Comment by SergK** [comment]
Hi @jmlrt, do you have any ETA on merging this PR? I want to get rid off my fork :( and use upstream as much as possible,
Thank you!

**Comment by jmlrt** [comment]
Hi @SergK, 
Sorry for the very long delay, we wanted to find a different way to fix it and just merged #549 which allows redirections in readiness probe.
Could you check if that fixes your issue?

**Comment by SergK** [comment]
@jmlrt thank you, Works for me!

**Comment by jmlrt** [comment]
Great! Thank you for your work and for waiting so long.

**Pull request closed without merging**
