### PR TITLE
duplicate label removed

### PR DESCRIPTION
**Pull request by mmisztal1980**
- [x] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [x] README.md updated with any new values or changes
- [ ] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

### CODE REVIEW

**Comment by mmisztal1980** [comment]
This PR is to address an issue I've run into when rendering the chart using HELM and deploying with Kubectl. The error message in Azure DevOps is:
- `duplicated mapping key at line 40, column 31:`

Upon closer examination, a fragment of the rendered stateful set looks like this:
```yaml
template:
    metadata:
      name: "microk8s-master"
      labels:
        heritage: "Helm"
        release: "elk-es"
        chart: "elasticsearch"
        app: "microk8s-master"
        app: "microk8s-master"
```
The duplicate `app` key is caused by it's dual presence in the HELM template, which is being addressed by this PR

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by mmisztal1980** [comment]
awesome, @jmlrt  when do you think this will be available in the chart itself?

**Comment by jmlrt** [comment]
- If you're deploying the chart [using master branch](https://github.com/elastic/helm-charts/blob/master/elasticsearch/README.md#using-master-branch), it's already available.

- If you're [using Helm repo](https://github.com/elastic/helm-charts/blob/master/elasticsearch/README.md#using-helm-repository), it will be available with next Elastic Stack release in a few weeks.

**Comment by mmisztal1980** [comment]
@jmlrt do you guys have an ETA for the next release? Didn't realize you guys were ok with having a broken chart in the registry for that long

**Comment by jmlrt** [comment]
@mmisztal1980  No ETA except that it will be released with the rest of Elastic Stack in a few weeks. 

Note that the chart is working well with GKE and and other tested k8s providers even with the duplicated label so we're not considering chart broken.

**Pull request merged**
