### PR TITLE
[7.x] [kibana] adding extra volumes and extra volume mounts

### PR DESCRIPTION
**Pull request by DilasserT**
- [x] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [x] README.md updated with any new values or changes
- [x] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

Related to #557 

Adding options to mount additionnal volumes with `extraVolumes` and `extraVolumeMounts` through `values.yaml`

### CODE REVIEW

**Review by ebuildy — APPROVED** [review]
Super!

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by jmlrt** [comment]
Hi @DilasserT, changes looks fine, however PR should target master branch with backport PR handled by Elastic maintainer. Can you reopen it to master branch?

**Comment by jmlrt** [comment]
Also some changes are required to make [Black](https://black.readthedocs.io/en/stable/) formatter happy in [elastic+helm-charts+pull-request+lint-python/1001](https://devops-ci.elastic.co/job/elastic+helm-charts+pull-request+lint-python/1001/label=docker&&virtual&&ubuntu-18.04/console).

Can you run `black kibana/tests/kibana_test.py`?

**Comment by ebuildy** [comment]
?

**Comment by DilasserT** [comment]
I will reopen on master

**Pull request closed without merging**
