### PR TITLE
allow array values for extra

### LINKED ISSUE #1451: Allow array values for extra
**Chart version:**
7.15.10

**Kubernetes version:**
v1.21.5

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
Docker for Mac

**Helm Version:**
v3.3.4

**`helm get release` output**

e.g. `helm get elasticsearch` (replace `elasticsearch` with the name of your helm release)

*Be careful to obfuscate every secrets (credentials, token, public IP, ...) that could be visible in the output before copy-pasting.*

*If you find some secrets in plain text in `helm get release` output you should use [Kubernetes Secrets](https://kubernetes.io/docs/concepts/configuration/secret/) to managed them is a secure way (see [Security Example](https://github.com/elastic/helm-charts/blob/master/elasticsearch/examples/security/values.yaml#L23-L38)).*

<details>
<summary>Output of helm get release</summary>

```
```

</details>

**Describe the bug:**
According to `https://github.com/elastic/helm-charts/blob/main/logstash/values.yaml` this should work
```
extraVolumes:
  - name: extras
     emptyDir: {}

extraVolumeMounts:
  - name: extras
     mountPath: /usr/share/extras
     readOnly: true
```

but I get this error when I run `helm install`
```
Error: template: charts/logstash/templates/statefulset.yaml:143:14: executing "charts/logstash/templates/statefulset.yaml" at <.Values.extraVolumes>: wrong type for value; expected string; got []interface {}
```

**Steps to reproduce:**

1. Set extraVolumes and extraVolumeMounts
```
extraVolumes:
  - name: extras
     emptyDir: {}

extraVolumeMounts:
  - name: extras
     mountPath: /usr/share/extras
     readOnly: true
```
2. `helm install logstash`

**Expected behavior:**
Volume should be created, but instead there's an error message

**Provide logs and/or server output (if relevant):**

*Be careful to obfuscate every secrets (credentials, token, public IP, ...) that could be visible in the output before copy-pasting*

```
```

**Any additional context:**
Issue is fixed with with https://github.com/elastic/helm-charts/pull/1450

### PR DESCRIPTION
**Pull request by dmarcs**
- [x] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [x] README.md updated with any new values or changes
- [ ] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

According to `https://github.com/elastic/helm-charts/blob/main/logstash/values.yaml` this should work
```
extraVolumes:
  - name: extras
     emptyDir: {}

extraVolumeMounts:
  - name: extras
     mountPath: /usr/share/extras
     readOnly: true
```

but I get this error when I run `helm install`
```
Error: template: charts/logstash/templates/statefulset.yaml:143:14: executing "charts/logstash/templates/statefulset.yaml" at <.Values.extraVolumes>: wrong type for value; expected string; got []interface {}
```

Fix #1451

### CODE REVIEW

**Comment by dugouchet** [comment]
same issue ..

**Comment by dugouchet** [comment]
looks the issue is solved in the conversation : https://github.com/elastic/helm-charts/issues/1182

**Review by jmlrt — APPROVED** [review]
LGTM⛴

**Comment by jmlrt** [comment]
ok to test

**Comment by jmlrt** [comment]
ok to test

**Comment by jmlrt** [comment]
ok to test

**Pull request merged**
