### PR TITLE
[filebeat][metricbeat] Update documentation on port collisions for multiple beats agents with hostNetworking enabled.

### LINKED ISSUE #995: Metric Beats and Filebeats collide with hostNetworking enabled.
**Chart version:** 7.10

**Kubernetes version:** 1.19

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine) Docker-Desktop

**Helm Version:** 3

**Describe the bug:**
Using metricbeat and filebeat helm charts with hostNetworking enabled collide on ports.

**Steps to reproduce:**

1. Helm install metricbeats with hostNetworking set to true
2. Helm install filebeat with hostNetworking set to true
3. Filebeat will fail to setup it's HTTP Server on port 5066.

Disabling the hostNetworking feature on either of the helm charts s

**Expected behavior:**
Default values for hostNetworking should not collide. 
We are integrating with elastic cloud and want auto-scaling daemonsets for our kubernetes nodes for metrics and logs.

I suggest the default values for one of the ports should change.

**Provide logs and/or server output (if relevant):**

kubectl logs filebeat-filebeat-qtb4b
2020-12-21T21:03:23.799Z        INFO    instance/beat.go:645    Home path: [/usr/share/filebeat] Config path: [/usr/share/filebeat] Data path: [/usr/share/filebeat/data] Logs path: [/usr/share/filebeat/logs]
2020-12-21T21:03:23.799Z        INFO    instance/beat.go:653    Beat ID: 512fcc30-bdf3-4b6a-a875-8c219a5b402e
2020-12-21T21:03:23.799Z        INFO    instance/beat.go:412    filebeat stopped.
2020-12-21T21:03:23.799Z        ERROR   instance/beat.go:956    Exiting: could not start the HTTP server for the API: listen tcp 127.0.0.1:5066: bind: address already in use
Exiting: could not start the HTTP server for the API: listen tcp 127.0.0.1:5066: bind: address already in use

### PR DESCRIPTION
**Pull request by kwsorensen**
- [x] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [x] README.md updated with any new values or changes
- [ ] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

Fix #995

### CODE REVIEW

**Comment by kwsorensen** [comment]
I signed the CLA before I created the pull request. Does it take a certain amount of time to get reflected? Otherwise I can post a copy if it here if needed.

**Review by jmlrt — APPROVED** [review]
LGTM⛴

**Comment by jmlrt** [comment]
cla/check

**Comment by jmlrt** [comment]
cla/check

**Comment by jmlrt** [comment]
cla/check

**Comment by jmlrt** [comment]
> I signed the CLA before I created the pull request. Does it take a certain amount of time to get reflected? Otherwise I can post a copy if it here if needed.

I think that's because f109f67d32fc8fec76863a00ccc108f683c034d4 is created with a different email.

Could you amend this commit to change author email?

**Comment by kwsorensen** [comment]
@jmlrt good catch. I just signed the CLA for ksorensen@scramsystems.com.

**Pull request merged**
