### PR TITLE
[elasticsearch] Added health pod name override for compatibility

### PR DESCRIPTION
**Pull request by tomhobson**
- [x] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [x] README.md updated with any new values or changes
- [ ] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

Could not see the name overrides contained within the README.md, I can add them if needed.

This is to add support for tools like 
https://github.com/roboll/helmfile and https://jenkins-x.io/v3/

As they generate a new pod each time, this creates a lot of noise and can cause merge conflicts, being able to override the health pod name prevents the pod being recreated when nothing has changed and enables smooth sailing.

### CODE REVIEW

**Review by jmlrt — APPROVED** [review]
LGTM⛴

**Comment by jmlrt** [comment]
jenkins test this please

**Review by jmlrt — CHANGES_REQUESTED** [review]
While the code LGTM, could you add a bit more details about why this is needed?

[`"helm.sh/hook-delete-policy": hook-succeeded`](https://github.com/elastic/helm-charts/blob/master/elasticsearch/templates/test/test-elasticsearch-health.yaml#L12) clean the test pod when test is successful.

Also [`"{{ .Release.Name }}-{{ randAlpha 5 | lower }}-test"`](https://github.com/elastic/helm-charts/blob/master/elasticsearch/templates/test/test-elasticsearch-health.yaml#L5) should ensure that 2 different releases deployend in the same namespace should generate different pod names.

>Could not see the name overrides contained within the README.md, I can add them if needed

`nameOverride` is described in https://github.com/elastic/helm-charts/blob/master/elasticsearch/README.md#L141, `healthNameOverride` should also have its description if this change is still needed.

**Comment by tomhobson** [comment]
Yeah so, Helmfile generates all of the charts and values into one directory. This is then commited to a github repository for helm to run upgrades on.

With randomly generated names it means that every time a commit is done to the cluster repo, a new elasticsearch test pod is made. This is especially annoying when you have multiple commits at once, as it creates merge conflicts for the cluster PRs. Having to manually fix your CI/CD every hour is very annoying.

We've removed elasticsearch from our cluster for this reason 

Allowing a health pod name override just means that if this pod is already created, it wont regenerate it and cause conflicts. If we add some new values to elasticsearch or upgrade the version, it will recreate.
I don't think it has any impact on functionality.

(Apologies for the Readme, fix incoming)

**Review by jmlrt — APPROVED** [review]
LGTM⛴

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by jmlrt** [comment]
unrelated errors, merging

**Pull request merged**
