### PR TITLE
Allow customization of the Statefulset

### PR DESCRIPTION
**Pull request by tproenca**
I added `extraVolumes`, `extraVolumesMounts`, `extraInitContainers` and `persistence.annotations` to the helm chart.

The `extraInitContainers` is useful in a situation that you want to add an init-container to get the data from a backup copy for example. You can mount the volume from the `volumeClaimTemplate`, and copy the data there.

The `extraVolumes`, `extraVolumesMounts` can be used to mount the logs folder in a particular volume, and use a sidecar container like `fluentd` to send the logs elsewhere.

The persistence annotations is a good addition for clusters that don't support the `storageClassName` yet.

### CODE REVIEW

**Comment by Crazybus** [comment]
As another note it also seems like you still need to sign the [CLA](https://www.elastic.co/contributor-agreement).

**Comment by tproenca** [comment]
> This looks great! Thanks for adding these in :)
> 
> Could you also please adding the following:
> 
> 1. Add the new values into the [README](https://github.com/elastic/helm-charts/blob/master/elasticsearch/README.md)
> 2. Add some tests for testing the templating logic. You can base it off the example for [extraEnvs](https://github.com/elastic/helm-charts/blob/226911d36f9e453bc2148370ef7f82a39ad56367/elasticsearch/tests/elasticsearch_test.py#L248-L256). Just a single test to ensure that it works correctly and has the right indentation level is enough.

All done. I'm waiting for my company approve the CLA on my side.

**Comment by tproenca** [comment]
I signed the CLA, but the merging is still blocked.

**Comment by Crazybus** [comment]
jenkins test this please

**Comment by tproenca** [comment]
Np... I'm glad to contribute. :)

**Pull request merged**
