### PR TITLE
[elasticsearch][logstash]Fix PodSecurityPolicy error in v1.22

### LINKED ISSUE #1643: [logstash] PodSecurityPolicy - no policy/v1, deprecation since k8s 1.22+
**Chart version:**
7.17.1

**Kubernetes version:**
1.22+

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
EKS

**Helm Version:**
3.8.1

**Describe the bug:**
https://github.com/elastic/helm-charts/pull/1420 
introduced this
```
 apiVersion: policy/v1
{{- else}}
apiVersion: policy/v1beta1
{{- end }}
kind: PodSecurityPolicy
```

but there is no _policy/v1_ for _PodSecurityPolicy_, this will be removed completely. 
The change was done in the context of _PodDisruptionBudget_, which has a _policy/v1_, but _PodSecurityPolicy_ has not.

Futher reading:

https://kubernetes.io/docs/reference/using-api/deprecation-guide/#psp-v125
_PodSecurityPolicy in the policy/v1beta1 API version will no longer be served in v1.25, and the PodSecurityPolicy admission controller will be removed.
PodSecurityPolicy replacements are still under discussion, but current use can be migrated to 3rd-party admission webhooks now._

https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/
_Kubernetes 1.21 starts the deprecation process for PodSecurityPolicy. As with all feature deprecations, PodSecurityPolicy will continue to be fully functional for several more releases. The current plan is to remove PSP from Kubernetes in the 1.25 release._

**Expected behavior:**
evaluate and switch to alternatives until k8s v1.25 arrives - this is just meant as a heads-up

### PR DESCRIPTION
**Pull request by faruryo**
Fix PodSecurityPolicy error in v1.22

There is no kind: PodSecurityPolicy in apiVersion: policy/v1

- [ ] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [ ] README.md updated with any new values or changes
- [ ] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

close #1643

### CODE REVIEW

**Comment by faruryo** [comment]
Contributor Agreement has been signed.

**Comment by jonkerj** [comment]
I'd like to bump this PR, as we really could use it. Seems like a maintainer only needs to kick off the CI/CD and we are golden.

**Comment by jonkerj** [comment]
@jmlrt , you seem an active maintainer of this repo, is there anything blocking this PR/issue? It is really trivial, easy to test and removes a blocker for a lot of people.

**Comment by jonkerj** [comment]
I find it a bit frustrating that this (for us blocking) issue with a PR does not seem to get any attention from devs/repo owners. This is not a good way to embrace contribution from the community. I understand that time is scarce know how priorities work, but I think any reply is better than leaving contributors in the dark for months.

@jmlrt, @Crazybus, @framsouza, @ebuildy (you seem active in this repo), could you please gives this issue/PR some love?

**Review by jmlrt — APPROVED** [review]
LGTM⛴

**Pull request merged**
