### PR TITLE
[kibana] adding extra volumes and extra volume mounts (#557)

### PR DESCRIPTION
**Pull request by DilasserT**
- [x] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [x] README.md updated with any new values or changes
- [x] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

PR Following #1247 

Adding options to mount additionnal volumes with `extraVolumes` and `extraVolumeMounts` through `values.yaml`

@jmlrt kibana/tests/kibana_test.py formatted using `black`

### CODE REVIEW

**Comment by DilasserT** [comment]
Not sure why the CLA check does not pass, I resigned it and tried to refresh the PR with no success

**Comment by jmlrt** [comment]
cla/check

**Comment by DilasserT** [comment]
What can I do to resolve this ?

**Comment by DilasserT** [comment]
Committed with the wrong user...

**Comment by DilasserT** [comment]
@jmlrt Is this PR alright ?

**Review by jmlrt — APPROVED** [review]
LGTM⛴

**Comment by jmlrt** [comment]
jenkins test this please

**Pull request merged**
