### PR TITLE
added loadBalancerIP option to service

### PR DESCRIPTION
**Pull request by adulescentulus**
- [x] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [x] README.md updated with any new values or changes
- [x] Updated template tests in `${CHART}/tests/*.py` 

opened to address #257 feature request which I need in a project. The old #323 somehow got stale.

### CODE REVIEW

**Comment by jmlrt** [comment]
Hi @adulescentulus,
Thanks for your PR.
Can you sign the CLA: https://www.elastic.co/contributor-agreement

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by adulescentulus** [comment]
@jmlrt I signed the CLA about 8 hours ago and got a pdf. I don't know what's next. Is there a manual processing step left?

**Comment by jmlrt** [comment]
cla/check

**Comment by jmlrt** [comment]
cla/check

**Comment by jmlrt** [comment]
> @jmlrt I signed the CLA about 8 hours ago and got a pdf. I don't know what's next. Is there a manual processing step left?

CLA check is done automatically. However it seems you signed it with your personnal email while the git commit has been done with some corporate email.

Can you change your commit email to the one you used to sign CLA?

You should be able to do that with the following commands:

```shell
git commit --amend --author="John Doe <john@doe.org>"
git push --force-with-lease
```

**Comment by adulescentulus** [comment]
@jmlrt  thanks for the hint. I fixed my mail address and now CLA passes and I hope the CI as it did locally

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by adulescentulus** [comment]
sorry just merged from master and so needs rebuild, didn't expect someone to be awake
But I don't understand why the build [failed](https://devops-ci.elastic.co/job/elastic+helm-charts+pull-request+lint-python/65/label=docker&&virtual&&ubuntu-18.04/console). Local `make test` works

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by adulescentulus** [comment]
aaahh now I get it: between two functions there need to be *two* blank lines, not one like I did. I need to fix this, don't I?

**Comment by jmlrt** [comment]
> aaahh now I get it: between two functions there need to be _two_ blank lines, not one like I did. I need to fix this, don't I?

Oh yes sorry, I relaunched the test without checking logs.

Indeed our python lint test is using [black](https://github.com/psf/black) and requires 2 new lines between each functions.

**Comment by adulescentulus** [comment]
finally hope everything is good to go now.

but why did `make test` did not report anything locally?

**Comment by jmlrt** [comment]
> but why did `make test` did not report anything locally?

python lint job is using [`make lint-python`](https://github.com/elastic/helm-charts/blob/master/helpers/common.mk#L31)

**Comment by jmlrt** [comment]
jenkins test this please

**Pull request merged**
