### PR TITLE
[elasticsearch] Fix spelling

### PR DESCRIPTION
**Pull request by cospeedster**
- [x] Fix spelling in `values.yaml`

### CODE REVIEW

**Comment by jmlrt** [comment]
cla/check

**Comment by jmlrt** [comment]
Hi @cospeedster,
Thanks for your PR.
Can you sign the CLA: https://www.elastic.co/contributor-agreement

**Review by jmlrt — APPROVED** [review]
LGTM⛴

**Comment by cospeedster** [comment]
Signed the CLA

**Review by jmlrt — APPROVED** [review]
LGTM⛴

**Comment by jmlrt** [comment]
backported to `6.8` and `7.x` branches

**Pull request merged**
