### PR TITLE
[filebeat] add permission to list nodes

### LINKED ISSUE #703: filebeat deployment in k8s failes to list nodes
Chart version:
7.8.0
Kubernetes version:
v1.16.8
Kubernetes provider: E.g. GKE (Google Kubernetes Engine)
AWS EKS
Helm Version:
v3.2.4

Missing permission to list nodes:
`github.com/elastic/beats/libbeat/common/kubernetes/watcher.go:146: Failed to list *v1.Node: nodes "ip-x-x-x-x.us-west-2.compute.internal" is forbidden: User "system:serviceaccount:elastic:filebeat-filebeat" cannot list resource "nodes" in API group "" at the cluster scope`

### PR DESCRIPTION
**Pull request by bmilescu**
- [ ] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [ ] README.md updated with any new values or changes
- [ ] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

Fix #703

### CODE REVIEW

**Comment by bmilescu** [comment]
I actually missed explaining why this is needed:
https://github.com/elastic/helm-charts/issues/703

In order to add extra metadata:
`filebeat.autodiscover:
      providers:
        - type: kubernetes
          node: ${NODE_NAME}
          hints.enabled: true
          add_resource_metadata:
            namespace.enabled: true
            node.enabled: true`

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by jmlrt** [comment]
cla/check

**Comment by jmlrt** [comment]
backported to `6.8`, `7.8`and `7.x` branches

**Pull request merged**
