### PR TITLE
added psp policy to filebeat

### PR DESCRIPTION
**Pull request by D1abloRUS**
- [x] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [x] README.md updated with any new values or changes
- [x] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

### CODE REVIEW

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by krichter722** [comment]
@D1abloRUS I'd be happy if you rebase this PR on master in order to push it forward - I'm not a dev, but a user who thinks that this is desperately needed. Is no one testing their operations with upcoming GKE alpha clusters?

**Comment by D1abloRUS** [comment]
@krichter722  I need to fix the tests, I don’t have time yet, the code is working, you can take it, then update the version of the chart

**Comment by jmlrt** [comment]
@krichter722 would you be interested to add Filebeat PSP to #496 or #641?

**Comment by D1abloRUS** [comment]
jenkins test this please

**Comment by D1abloRUS** [comment]
@jmlrt run test pls

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by jmlrt** [comment]
Some changes are required to make [Black](https://black.readthedocs.io/en/stable/) formatter happy in https://devops-ci.elastic.co/job/elastic+helm-charts+pull-request+lint-python/463/label=docker&&virtual&&ubuntu-18.04/console.

Can you run `black <CHART>/tests/<CHART>_test.py`?

Also Python tests are failing: https://devops-ci.elastic.co/job/elastic+helm-charts+pull-request+template-testing/842/CHART=filebeat,label=docker&&virtual/console

**Pull request closed without merging**
