### PR TITLE
[7.x][FILBEAT] Add ability to set PVC/persistence on filebeat deployement

### PR DESCRIPTION
**Pull request by disaster37**
Signed-off-by: disaster37 <linuxworkgroup@hotmail.com>

- [X] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [X] README.md updated with any new values or changes
- [X] Updated template tests in `${CHART}/tests/*.py` 
- [X] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

We can now set persistence when use filebeat as deployement to store registry file.

### CODE REVIEW

**Comment by jmlrt** [comment]
Hi @DilasserT, PR should target master branch with backport PR handled by Elastic maintainer. Can you reopen it to master branch?

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by jmlrt** [comment]
Some changes are required to make [Black](https://black.readthedocs.io/en/stable/) formatter happy in [elastic+helm-charts+pull-request+lint-python/1002](https://devops-ci.elastic.co/job/elastic+helm-charts+pull-request+lint-python/1002/label=docker&&virtual&&ubuntu-18.04/console).

Can you run `black filebeat/tests/filebeat_test.py`?

**Comment by disaster37** [comment]
It's done

**Comment by disaster37** [comment]
Any news ?

**Comment by jmlrt** [comment]
Hi @disaster37, can you reopen the PR on the master branch as mentioned in https://github.com/elastic/helm-charts/pull/1242#issuecomment-866902525?

**Pull request closed without merging**
