### PR TITLE
[elasticsearch] add value to disable tests

### PR DESCRIPTION
**Pull request by nflaig**
It should be possible to disable the tests of the chart. This is especially important if the chart is used as a subchart which means the test are also executed if you run `helm test`. For some users it might not be desirable to run the test provided by the elastic helm chart, the value gives the user of the chart the option to configure this.

- [x] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [x] README.md updated with any new values or changes
- [ ] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

### CODE REVIEW

**Review by jmlrt — COMMENTED** [review]
Thanks for this PR, can you update the README with this new value?

**Comment by nflaig** [comment]
@jmlrt Thanks again for the review! I updated the README with the new value

**Comment by nflaig** [comment]
@jmlrt any update on this? Let me know if I should apply further changes

**Review by jmlrt — APPROVED** [review]
Fixed the conflict. Change LGTM. As a minor improvement, I think it could be great to also add a `{{- if .Values.tests.enabled -}}` condition to not print test command when the test is disabled.

https://github.com/elastic/helm-charts/blob/0e5a168fdcdab22cb9ed2f89e5ccb79e6c4d82fd/elasticsearch/templates/NOTES.txt#L3-L4

**Review by jmlrt — APPROVED** [review]
LGTM⛴

**Comment by jmlrt** [comment]
jenkins test this please

**Pull request merged**
