### PR TITLE
[elasticsearch] Reworked the way to mapping node roles. Node roles are mapped as "nod…

### PR DESCRIPTION
**Pull request by maximchukm**
I had experienced a problem when I tried to set up nodes data tiers through "roles" parameter.
During ElasticSearch pod starting I had the error: "unknown setting [node.data_cold] please check that any required plugins are installed", as well as I found another message caused by the same way to set roles: "[node.master] setting was deprecated in Elasticsearch and will be removed in a future release!"
According to this, I reworked the node roles setting.

### CODE REVIEW

**Comment by ebuildy** [comment]
hello, tests are running fine?

**Comment by maximchukm** [comment]
> hello, tests are running fine?

Hello, I've just checked it and updated couple assertions for a new environment variable. Now they're running fine.

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by jmlrt** [comment]
Hi @maximchukm, thanks for this PR.
This will need a bit more investigation in our side to ensure this is the way we want it to be implemented.

Related to #855

**Review by jmlrt — COMMENTED** [review]
Hi @maximchukm, many thanks for your work on this PR 🙏🏻 .

I had some issues during review and tests and I had to rework the implementation which needed a bit more refactoring in https://github.com/elastic/helm-charts/pull/1186.

**Comment by maximchukm** [comment]
> Hi @maximchukm, many thanks for your work on this PR 🙏🏻 .
> 
> I had some issues during review and tests and I had to rework the implementation which needed a bit more refactoring in #1186.

Sounds great, looking forward to using the new way of role setting!

**Comment by jmlrt** [comment]
Closing as it was implemented in https://github.com/elastic/helm-charts/pull/1186

**Pull request closed without merging**
