### PR TITLE
[elasticsearch] add support for loadBalancerSourceRanges

### PR DESCRIPTION
**Pull request by ta-ando**
- [x] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [x] README.md updated with any new values or changes
- [x] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

### CODE REVIEW

**Comment by jmlrt** [comment]
cla/check

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by jmlrt** [comment]
Hi @ta-ando, 
Our [lint-python](https://devops-ci.elastic.co/job/elastic+helm-charts+pull-request+lint-python/10/label=docker&&virtual&&ubuntu-18.04/console) test is failing.
Can you reformat the file with [black](https://black.readthedocs.io/en/stable/) to make the test pass?

**Comment by ta-ando** [comment]
Hi @jmlrt,
I reformat the test I wrote.

**Comment by jmlrt** [comment]
jenkins test this please

**Pull request merged**
