### PR TITLE
[logstash] Add logstashPipelineFiles param to logstash templates

### PR DESCRIPTION
**Pull request by asbubam**
- [x] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [x] README.md updated with any new values or changes
- [ ] Updated template tests in `${CHART}/tests/*.py` 
- [x] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

* Add logstashPipelineFiles param to logstash templates
* Allows user to add any pipeline files in `/usr/share/logstash/pipeline/` from user's local files
* Ex) values.yaml
```yaml
logstashPipelineFiles: "pipeline/*.conf"
```

### CODE REVIEW

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by asbubam-benx** [comment]
jenkins test this please

**Comment by asbubam-benx** [comment]
@jmlrt Thanks for your checking. Could you request jenkins testing again, plz?

**Comment by asbubam** [comment]
@jmlrt Thanks for your checking. Could you request jenkins testing again, plz?

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by jmlrt** [comment]
@asbubam, can you merge master on your branch?

**Comment by asbubam** [comment]
@jmlrt Yes! Sure. I did. Thanks.

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by jmlrt** [comment]
It looks like test is failing: https://devops-ci.elastic.co/job/elastic+helm-charts+pull-request+integration-logstash/334/KUBERNETES_VERSION=1.14,LOGSTASH_SUITE=elasticsearch,label=docker&&virtual/console

**Pull request closed without merging**
