### PR TITLE
[metricbeat] support deployment/daemonset specific metrics

### LINKED ISSUE #812: Support metricbeat deployment labels
**Describe the feature:**
Would be great, if `labels` property would add labels to `metricbeat` Deployment the same as it does for [DaemonSet](https://github.com/elastic/helm-charts/blob/master/metricbeat/templates/daemonset.yaml#L12-L14)

**Describe a specific use case for the feature:**
I use labels to define Kubernetes network-policies. I try to add a custom label to metricbeat pods. It perfectly works for DaemonSet, but not for Deployment

### PR DESCRIPTION
**Pull request by v1r7u**
- [x] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [x] README.md updated with any new values or changes
- [x] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

Closes #812

Turned out, initially labeling was completely implemented for DaemonSet (both daemon-set and pod labels), but only partially for Deployment (only pod-level labels). I decided to make these properties to be consistent for both object types, while still keeping to the design we agreed in the linked issue

### CODE REVIEW

**Comment by v1r7u** [comment]
I think I've signed the Agreement yesterday evening. Should I re-create the PR or you can re-run the check?

**Comment by jmlrt** [comment]
jenkins test this please

**Review by jmlrt — APPROVED** [review]
LGTM, just a nit on test naming

**Comment by jmlrt** [comment]
jenkins test this please

**Review by jmlrt — APPROVED** [review]
LGTM⛴

**Comment by jmlrt** [comment]
backported to `6.8`, `7.9` and `7.x` branches

**Pull request merged**
