### PR TITLE
[kibana] added plugins support

### PR DESCRIPTION
**Pull request by NorDroN**

### CODE REVIEW

**Comment by elasticcla** [comment]
Hi @NorDroN, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in your Git [commit](https://github.com/elastic/helm-charts/pull/285.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by RobertoUa** [comment]
is there any chance it will be released any time soon?

**Comment by cryptobioz** [comment]
Do you have any update of this?

**Comment by japzio** [comment]
@livanov

**Comment by acarsercan** [comment]
Any updates?

**Comment by borancar** [comment]
This seems to need approval from a reviewer with write access, potentially @jmlrt ?

**Comment by jmlrt** [comment]
Hi @acarsercan @borancar, I'm sorry we still didn't take the time to test this correctly.

While we may eventually merge this, we still recommend building custom Kibana images to use plugins as mentioned [here](https://github.com/elastic/helm-charts/issues/246#issuecomment-568712211) and [here](https://github.com/elastic/helm-charts/tree/master/kibana#how-to-install-plugins).

**Pull request closed without merging**
