### PR TITLE
[elasticsearch] _helpers.tpl - elasticsearch.endpoints to use elasticsearch.uname

### PR DESCRIPTION
**Pull request by xario**
This addressing an issue where nodes are unable to locate the masters when `fullnameOverride` is used, due to the `cluster.initial_master_nodes` having the wrong name of the nodes.

- [x] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [ ] README.md updated with any new values or changes
- [x] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

### CODE REVIEW

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by xario** [comment]
> jenkins test this please

I have added a test case which covers the use case.

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by jmlrt** [comment]
backported to `6.8`, `7.8`and `7.x` branches

**Pull request merged**
