### PR TITLE
[meta] add config for backport

### PR DESCRIPTION
**Pull request by jmlrt**
This commit add the config file to manage backport PR using
https://github.com/sqren/backport

### CODE REVIEW

**Review by sqren — APPROVED** [review]
lgtm 👍 
lmk how it goes.

**Review by Conky5 — APPROVED** [review]

**Comment by jmlrt** [comment]
Admin merging as the transient issues are not related.

**Comment by jmlrt** [comment]
@sqren thanks for your help and review.

Can you tell me if we need to backport this PR so `.backportrc.json` exists in `6.8`, `7.10` and `7.x` branches or is it enough to have it in `master` branch?

**Comment by sqren** [comment]
While not required it's a good idea to have it on any branch a developer might checkout locally. 
This is because when running the backport script it will look for the config locally, do if a user is on a branch without a config it won't work.

**Pull request merged**
