### PR TITLE
[elasticsearch] add loadBalancer externalTrafficPolicy option

### PR DESCRIPTION
**Pull request by luanguimaraesla**
- [X] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [X] README.md updated with any new values or changes
- [X] Updated template tests in `${CHART}/tests/*.py` 
- [X] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

Hello,

This PR adds a new option in the `elasticsearch` service spec in order to support configuration for externalTrafficPolicy if the service is a loadBalancer.

Reference: https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip

### CODE REVIEW

**Comment by luanguimaraesla** [comment]
I've just signed the CLA, should I do anything else?

**Comment by jmlrt** [comment]
jenkins test this please

**Review by jmlrt — APPROVED** [review]
LGTM⛴

**Comment by jmlrt** [comment]
backported to `6.8`, `7.9` and `7.x` branches

**Pull request merged**
