### PR TITLE
raw_input() was removed in Python 3

### PR DESCRIPTION
**Pull request by cclauss**
- [ ] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [ ] README.md updated with any new values or changes
- [ ] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

### CODE REVIEW

**Comment by Crazybus** [comment]
jenkins test this please

**Comment by cclauss** [comment]
Are the Jenkins tests run on Python 3?

**Comment by cclauss** [comment]
> there is nothing stopping us from switching things over to python3 besides time

https://pythonclock.org

**Comment by Crazybus** [comment]
> Are the Jenkins tests run on Python 3?

They run inside of a docker container defined here:

https://github.com/elastic/helm-charts/blob/581b08327de0e4a3e1ca1b3d478f4f4c9aa011f5/helpers/helm-tester/Dockerfile#L1-L10

So if you wanted to switch the python testing over to python3 you could do it all in one PR and switch out the image here.

**Pull request merged**
