### PR TITLE
[Kibana] Add support traefik, for expose 

### PR DESCRIPTION
**Pull request by zorgzerg**
- [x] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [x] README.md updated with any new values or changes
- [ ] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

### CODE REVIEW

**Comment by zorgzerg** [comment]
Hmmm... I'm signed CLA, but check not passed. What am I doing wrong

**Comment by elasticcla** [comment]
Hi @zorgzerg, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in your Git [commit](https://github.com/elastic/helm-charts/pull/487.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by elasticcla** [comment]
Hi @zorgzerg, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in your Git [commit](https://github.com/elastic/helm-charts/pull/487.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by zorgzerg** [comment]
Ohhh... Sorry, apparently I was in a hurry. Now everything is ok

**Comment by zorgzerg** [comment]
Fixed

**Comment by jmlrt** [comment]
jenkins test this please

**Pull request closed without merging**
