### PR TITLE
[logstash] Restart the logstash pod when the secrets have changed

### LINKED ISSUE #714: [logstash] Reload k8s pod if the k8s secrets changed
**Describe the feature:**
Restart k8s pod when secrets changed
Should to add `secretsechecksum` to the statefulset annotation.    

**Describe a specific use case for the feature:**
We updated secrets which mounted to the statefulset, but pod know about the only old secrets, pod should be restarted as in the case of `logstash-config` changed.

I can prepare  the **PR**.

### PR DESCRIPTION
**Pull request by kksudo**
- [x] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [ ] README.md updated with any new values or changes
- [x] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

Fix #714

### CODE REVIEW

**Comment by kksudo** [comment]
@jmlrt Could you run the Jenkins CI, please?

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by jmlrt** [comment]
The errors don't seem related but I'd like to do a few manual test before merging

**Comment by kksudo** [comment]
Any updates ?

**Comment by jmlrt** [comment]
backported to `6.8`, `7.8`and `7.x` branches

**Pull request merged**
