### PR TITLE
Added support for multiple storage volumes

### PR DESCRIPTION
**Pull request by cambierr**
- [x] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [x] README.md updated with any new values or changes
- [ ] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

This PR adds the support for multiple storage volumes.

Since this is my first PR, feel free to give any constructive feedback :-)

### CODE REVIEW

**Comment by jmlrt** [comment]
Hi @cambierr ,
Thanks for your PR.
Can you sign the CLA: https://www.elastic.co/contributor-agreement

**Comment by cambierr** [comment]
Hi @jmlrt ,
I actually signed it... twice... but it seems like it doesn't keep track of my signature... will try again

**Comment by jmlrt** [comment]
closed by mistake while trying the new GitHub mobile app 😄 
it seems that CLA is OK now 👍

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by cambierr** [comment]
Hi @jmlrt 

Any chance for this to get merged soon ?

**Comment by jmlrt** [comment]
Hi @cambierr, sorry for the delay.
Can you add a little more context about your need to manage multiple storage volumes?

**Comment by cambierr** [comment]
Sure!

The main goal of this PR is to allow using several data volumes instead of a single one. The rationale behind that is that for most of our deployment scenarios(managed kubernetes services), we are limited by the per-volume bandwidth that kubernetes service provider offers, unless you go with very high grade stuff which then make running Elasticsearch on kubernetes quite costly.

Given the limited IO per volume, a very easy way to boost performances while keeping the price constant and the amount of Elasticsearch instances is therefore to be able to mount N data volumes per Elasticsearch pod. This way, given the same storage space, we benefit from N times the IO which greatly improves the quality of experience of large datasets.

**Comment by cambierr** [comment]
Hi @jmlrt 

I'm about to deploy my version of this chart on several clusters and was wondering if there is any chance for his one to get merged before ?

Regards,

**Comment by jmlrt** [comment]
Hi @cambierr,
I'm sorry, we don't have time to review and test it currently as we have other big priorities.
Feel free to deploy your version and keep the PR open and we hope being able to merge it later.

**Comment by Erog38** [comment]
Hey all, we need this functionality in the current chart for our production deployments, we've been running it for some time based off this PR and would love to see this in the official chart!

**Comment by jmlrt** [comment]
still valid

**Comment by jmlrt** [comment]
Hi @elastic/es-delivery, 

This PR is adding the capability to have more than one volume attached to each Elasticsearch pod.
https://github.com/elastic/helm-charts/pull/523#issuecomment-616733589 for more context.

Do you have any recommandations or specific things that we should pay attention for when using multiples volumes in Elasticsearch?

**Comment by mark-vieira** [comment]
I'm going to bring this up with the larger team. In general we don't recommend using multiple data paths but I don't think we actually deprecated this yet. I'll follow up.

**Comment by mark-vieira** [comment]
We intend to have some discussions around future support for multiple data paths next week after the holidays.

**Comment by mark-vieira** [comment]
The discussions on the future of multiple data paths is. Right now, we tentatively expect to have a decision on this topic in March. I'd hate to merge this in and effectively expand the usage of a feature that will subsequently be deprecated/removed in Elasticsearch. Right now I think the best thing to do is to hold off until a decision is made. If the decision is multiple data paths will stay around, and therefore, be properly supported in all case (right now there are awkward edge cases), then we can push forward on this.

**Comment by jmlrt** [comment]
> The discussions on the future of multiple data paths are still ongoing. Right now, we tentatively expect to have a decision on this topic in March. I'd hate to merge this in and effectively expand the usage of a feature that will subsequently be deprecated/removed in Elasticsearch. Right now I think the best thing to do is to hold off until a decision is made. If the decision is multiple data paths will stay around, and therefore, be properly supported in all case (right now there are awkward edge cases), then we can push forward on this.

Hi @mark-vieira,
Did you make some progress on this topic?

**Comment by mark-vieira** [comment]
The intent is to remove support for multiple data paths in Elasticsearch 8.0. Given that, I think it makes sense _not_ to add configuration support for a capability that will soon be removed.

**Comment by jmlrt** [comment]
Thanks for the details:+1:

**Pull request closed without merging**
