### PR TITLE
feat: adding liveness probe for kibana

### PR DESCRIPTION
**Pull request by keshavprasadms**
- [ ] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [ ] README.md updated with any new values or changes
- [ ] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

### CODE REVIEW

**Comment by jmlrt** [comment]
Hi @keshavprasadms, thank you for this PR, Kibana liveness probe wasn't defined for purpose.
We need to study if we can use the same probe as for readiness.

**Comment by jmlrt** [comment]
cla/check

**Comment by nikitakazantsev12** [comment]
> Hi @keshavprasadms, thank you for this PR, Kibana liveness probe wasn't defined for purpose.
> We need to study if we can use the same probe as for readiness.

Our practical experience shows, that we can use exactly the same probe as a liveness check (now we're achieving that patching existing Kibana-deployment of the Helm-chart).

**Comment by ecureuil** [comment]
Hi, unfortunalately this PR was automatically closed but the feature is still missing. @jmlrt do you want I recreate it, please?

**Pull request closed without merging**
