### PR TITLE
Add support to PodDisruptionBudget policy/v1

### LINKED ISSUE #1454: changed PodDisruptionBudget api to policy/v1 because it's failing in k8s version 1.21.2
**Chart version**: 7.15.0

**Kubernetes version**: 1.21.2

**Kubernetes provider**: AKS (Azure Kubernetes Service)

**Helm Version**: 3.7.1

**Describe the bug**: If we try the helm upgrade command with  elasticsearch helm chart 7.15.0 then is's failing due to the PodDisruptionBudget api version in AKS kubernetes version 1.21.2.

**Steps to reproduce**:

1. deploy elastcisearch helm chart 7.15.0 into AKS 1.21.2 version
2. try to upgrade the helm chart with some changes

**Expected behavior**: elasticsearch helm chart 7.15.0 should be upgraded with AKS kubernetes version 1.21.2.

**Provide logs and/or server output (if relevant)**: 
image

**Any additional context**: PR -> https://github.com/elastic/helm-charts/pull/1453

### LINKED ISSUE #1568: Elastic chart referencing deprecated construct PodDisruptionBudget
**Chart version: 7.16.3**

**Kubernetes version: Client Version: [version.Info](http://version.info/){Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: [version.Info](http://version.info/){Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:59:07Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}**

**Kubernetes provider: DockerDesktop** E.g. GKE (Google Kubernetes Engine)

**Helm Version: 3.8.0**
**Docker: Docker version 20.10.11, build dea9396**

**`helm get release` output**

e.g. `helm get elasticsearch` (replace `elasticsearch` with the name of your helm release)

*Be careful to obfuscate every secrets (credentials, token, public IP, ...) that could be visible in the output before copy-pasting.*

*If you find some secrets in plain text in `helm get release` output you should use [Kubernetes Secrets](https://kubernetes.io/docs/concepts/configuration/secret/) to managed them is a secure way (see [Security Example](https://github.com/elastic/helm-charts/blob/master/elasticsearch/examples/security/values.yaml#L23-L38)).*

<details>
<summary>Output of helm get release</summary>

```
```

</details>

**Describe the bug: Deployment of Elastic/Kibana/Filebeat helm chart results in warnings regarding deprecated constructs:  PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0203 09:53:25.831727 93370 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
W0203 09:53:25.833380 93370 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding
W0203 09:53:25.863538 93370 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0203 09:53:25.876382 93370 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
W0203 09:53:25.880616 93370 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding**

**Steps to reproduce: helm install myelk **

1. helm repo add elastic https://helm.elastic.co
2. helm install testelk elastic/elasticsearch
3. Observe command line output

**Expected behavior: No warnings due to deprecated constructs**

**Provide logs and/or server output (if relevant): W0203 09:53:25.825499 93370 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0203 09:53:25.831727 93370 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
W0203 09:53:25.833380 93370 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding
W0203 09:53:25.863538 93370 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0203 09:53:25.876382 93370 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
W0203 09:53:25.880616 93370 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding**

*Be careful to obfuscate every secrets (credentials, token, public IP, ...) that could be visible in the output before copy-pasting*

```
```

**Any additional context:**

### PR DESCRIPTION
**Pull request by framsouza**
This PR adds support to PodDisruptionBudget `policy/v1` & backward compatibility with `policy/v1beta1`, it will fix the deprecated message you might be getting during charts installation:

```
helm install es ../elasticsearch/ -f ../elasticsearch/values.yaml
W1015 15:55:59.468680   45578 warnings.go:67] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W1015 15:56:01.261764   45578 warnings.go:67] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
NAME: es
LAST DEPLOYED: Fri Oct 15 15:55:59 2021
NAMESPACE: default
STATUS: deployed
```

Fix #1454
Fix #1568
Replace #1453, #1526 and #1564

### CODE REVIEW

**Review by jmlrt — CHANGES_REQUESTED** [review]
TIL `.Capabilities.APIVersions.Has`, this is really nice 👍🏻 

I think that `elasticsearch/templates/podsecuritypolicy.yaml` and `logstash/templates/podsecuritypolicy.yaml` should also be updated, the rest LGTM.

**Review by jmlrt — APPROVED** [review]
LGTM⛴

**Comment by tomislater** [comment]
Hey 👋

What about this PR? Are we going to merge these changes?

**Comment by dantheperson** [comment]
Any plans to merge to the 6.8 branch?  We are stuck on 6.8 for a while as it's a big refactor job to update to the newer client libraries.

**Pull request merged**
