### PR TITLE
warn in reference to  #499

### PR DESCRIPTION
**Pull request by zeph**
- [x] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [ ] README.md updated with any new values or changes
- [ ] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

### CODE REVIEW

**Comment by zeph** [comment]
@elasticmachine I signed the CLA

**Comment by jmlrt** [comment]
cli/check

**Comment by jmlrt** [comment]
cla/check

**Comment by jmlrt** [comment]
should fix #499

**Comment by jmlrt** [comment]
jenkins test this please

**Pull request merged**
