### PR TITLE
[6.8] [meta] add tests for k8s 1.19 (#1231)

### PR DESCRIPTION
**Pull request by jmlrt**
Backports the following commits to 6.8:
 - [meta] add tests for k8s 1.19 (#1231)

### CODE REVIEW

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by jmlrt** [comment]
👋🏻 @elastic/observablt-robots, Filebeat chart tests are failing with Filebeat 6.8.17-SNAPSHOT and GKE/K8S 1.19:
- https://devops-ci.elastic.co/job/elastic+helm-charts+pull-request+integration-filebeat/988/FILEBEAT_SUITE=oss,KUBERNETES_VERSION=1.19,label=docker&&virtual/console
- https://devops-ci.elastic.co/job/elastic+helm-charts+pull-request+integration-filebeat/988/FILEBEAT_SUITE=security,KUBERNETES_VERSION=1.19,label=docker&&virtual/console
- https://devops-ci.elastic.co/job/elastic+helm-charts+pull-request+integration-filebeat/988/FILEBEAT_SUITE=upgrade,KUBERNETES_VERSION=1.19,label=docker&&virtual/console

Looking at the logs, it seems that Filebeat 6.8.17-SNAPSHOT don't push any logs to Elasticsearch and so the expected `filebeat-6.8.17` indice is missing in Elasticsearch.

Note that this test is working with:
- Filebeat 6.8.17-SNAPSHOT and GKE/K8S 1.17 / 1.18
- Filebeat 7.13.3-SNAPSHOT and GKE/K8S 1.17 / 1.18 / 1.19

I suspect this may be because Filebeat 6.8.X is using [Docker input](https://www.elastic.co/guide/en/beats/filebeat/6.8/filebeat-input-docker.html) instead of [Container input](https://www.elastic.co/guide/en/beats/filebeat/7.13/filebeat-input-container.html) and GKE/K8S 1.19 is using containerd instead of Docker now (https://cloud.google.com/kubernetes-engine/docs/concepts/using-containerd).

Did you had any issues with Filebeat 6.8 + Docker input and GKE 1.19 in your tests?

**Comment by v1v** [comment]
Hey @jmlrt , thanks for the heads up.

As far as I know we don't test the `6.8` versions in any of our test environments (https://github.com/elastic/observability-dev/blob/master/docs/observability-clusters.md#what-clusters-do-we-have-in-place)

Worth to put the @elastic/beats-contributors team in the loop in case they can provide further insights.

**Comment by kuisathaverat** [comment]
we have some tests on the e2e for those helm charts https://github.com/elastic/e2e-testing/tree/master/e2e/_suites/helm but we only test the 7.x and master versions at the moment. Also we test only k8s 1.18.2

https://beats-ci.elastic.co/job/e2e-tests/job/e2e-testing-helm-daily-mbp/

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by jmlrt** [comment]
jenkins test this please

**Pull request merged**
