### PR TITLE
kibana: fixed bogus request of 500 millibytes mem

### PR DESCRIPTION
**Pull request by accek**
- [x] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [x] README.md updated with any new values or changes
- [ ] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

### CODE REVIEW

**Comment by Crazybus** [comment]
jenkins test this please

**Comment by Crazybus** [comment]
jenkins test this please

**Comment by accek** [comment]
> LGTM!
> 
> Nice catch! Do you know if 500m is also invalid? 

500m is theoretically valid for memory, but useless. It is accepted by k8s and means 0.5 bytes (half a byte).

**Comment by Crazybus** [comment]
Thanks for clarifying! Now it makes sense why it never got caught.

**Pull request merged**
