### PR TITLE
optional labels for kibana ingress

### PR DESCRIPTION
**Pull request by paltryeffort**
I am running multiple IngressControllers and I need to add labels to my Ingress objects to select which controller to use.

Config example for values.yml:
```
ingress:
  enabled: true
  annotations:
    ingress.kubernetes.io/protocol: https
  labels:
    my-ingress: internal
```

### CODE REVIEW

**Comment by elasticcla** [comment]
Hi @paltryeffort, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in your Git [commit](https://github.com/elastic/helm-charts/pull/320.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by pbecotte** [comment]
I think you need to add a default for that to the values.yaml file as well?

**Comment by jmlrt** [comment]
Hi @paltryeffort,
Thanks for your PR.
Can you sign the CLA: https://www.elastic.co/contributor-agreement

**Comment by jmlrt** [comment]
jenkins test this please

**Pull request closed without merging**
