### PR TITLE
[metricbeat] bump kube-state-metrics to version 4.7.0

### LINKED ISSUE #1576: [metricbeat] kube-state-metrics incompatible with k8s v1.22
**Chart version:**
7.16.3

**Kubernetes version:**
1.22

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
K3s on Hetzner Cloud

**Describe the bug:**
The dependency kube-state-metrics isn't compatible with k8s v1.22 because it is using depricated and now removed apis = `rbac.authorization.k8s.io/v1beta1 ClusterRole`

**Steps to reproduce:**

1. Install a k8s cluster with v1.22
2. Try to install this helm chart

**Expected behavior:**
Deploys without any issues

**Any additional context:**
the repository https://charts.helm.sh/stable that you are using for kube-state-metrics is depricated and has been moved for this particular helm chart to https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-state-metrics
See issue https://github.com/kubernetes/kube-state-metrics/issues/1153 and https://github.com/helm/charts#deprecation-timeline for more information.

### PR DESCRIPTION
**Pull request by beatkind**
I have bumped the kube-state-metrics version referenced in the metricbeat chart. Otherwise, metricbeat does not work for k8s higher than 1.21.X.

- [X] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [ ] README.md updated with any new values or changes
- [ ] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

Fix #1576 
Replace #1577

### CODE REVIEW

**Comment by beatkind** [comment]
> ❌ Author of the following commits did not sign a [Contributor Agreement](https://www.elastic.co/contributor-agreement): [92137db](https://github.com/elastic/helm-charts/commit/92137db96694e697320976d98a712f2e07ccc63e)
> 
> Please, read and sign the above mentioned agreement if you want to contribute to this project

I just signed them

**Comment by peterbosalliandercom** [comment]
We are upgrading to Openshift 4.9 and this is mandatory because of 1.22 kubernetes. Can somebody please review this PR?

**Comment by Sir-Jacques** [comment]
We're upgrading to kubernetes 1.22 soon, reviewing/approving this change would be greatly appreciated! :-)

**Review by peterbosalliandercom — APPROVED** [review]
Approved

**Comment by peterbosalliandercom** [comment]
> > x Author of the following commits did not sign a [Contributor Agreement](https://www.elastic.co/contributor-agreement): [92137db](https://github.com/elastic/helm-charts/commit/92137db96694e697320976d98a712f2e07ccc63e)
> > Please, read and sign the above mentioned agreement if you want to contribute to this project
> 
> I just signed them

Looks like it is not signed correctly? Did you sign all commits?

**Comment by beatkind** [comment]
> > > x Author of the following commits did not sign a [Contributor Agreement](https://www.elastic.co/contributor-agreement): [92137db](https://github.com/elastic/helm-charts/commit/92137db96694e697320976d98a712f2e07ccc63e)
> > > Please, read and sign the above mentioned agreement if you want to contribute to this project
> > 
> > 
> > I just signed them
> 
> Looks like it is not signed correctly? Did you sign all commits?

Sorry, I was stupid on that one.

**Comment by beatkind** [comment]
@peterbosalliandercom can you re-review it please?

**Comment by lucagouty** [comment]
hello @peterbosalliandercom @beatkind, any news on this one? sorry to bump it but 1.21 end of life is getting very close

**Review by pruissen — APPROVED** [review]

**Review by pruissen — DISMISSED** [review]

**Review by SimonWillemsen — DISMISSED** [review]

**Comment by jmlrt** [comment]
ok to test

**Comment by jmlrt** [comment]
ok to test

**Pull request merged**
