### PR TITLE
[logstash] Add option loadBalancerIP to service

### PR DESCRIPTION
**Pull request by ebuildy**
Fix https://github.com/elastic/helm-charts/issues/1031

- [X] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [ ] README.md updated with any new values or changes
- [X] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

### CODE REVIEW

**Review by jmlrt — APPROVED** [review]
LGTM⛴

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by nittyy** [comment]
@jmlrt or @ebuildy, could you backport this fix to 7.x and 6.8 versions please ? This is needed for our production release scheduled at the first week of May, 2021.

**Comment by davidcharbonnier** [comment]
Hello @jmlrt and @ebuildy, we are also looking forward for this backport on our side for a few weeks now, when do you plan to backport this change?

**Comment by jmlrt** [comment]
@nittyy, @davidcharbonnier, @Ricardolaponder, this PR has been backported and should be part of next helm-charts releases.

**Pull request merged**
