### PR TITLE
[filebeat] fix(template): fullnameOverride if releaseName is "filebeat"

### PR DESCRIPTION
**Pull request by eyenx**
Signed-off-by: Toni Tauro <toni.tauro@adfinis.com>

- [x] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [ ] README.md updated with any new values or changes  # not needed
- [ ] Updated template tests in `${CHART}/tests/*.py` # not needed
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`  # not needed

### CODE REVIEW

**Comment by eyenx** [comment]
## before:

```
$ helm template filebeat .  | grep " name: "
  name: filebeat-filebeat
  name: filebeat-filebeat-config
  name: filebeat-filebeat-cluster-role
  name: filebeat-filebeat-cluster-role-binding
  name: filebeat-filebeat-cluster-role
  name: filebeat-filebeat
  name: filebeat-filebeat
```


## after:

```
$ helm template filebeat .  | grep " name: "   fix/filebeat-fullnameOverride ✔
  name: filebeat
  name: filebeat-daemonset-config
  name: filebeat-cluster-role
  name: filebeat-cluster-role-binding
  name: filebeat-cluster-role
  name: filebeat
  name: filebeat
      name: "filebeat"
      - name: filebeat-config
          name: filebeat-daemonset-config

```

**Comment by jmlrt** [comment]
Hi @eyenx,
Thanks for opening this PR.
We'll try to review it soon. Please be patient.

**Comment by eyenx** [comment]
No hurry

**Comment by jmlrt** [comment]
still valid

**Review by jmlrt — COMMENTED** [review]
Change looks good technically, however, I'm not sure we would want to merge it. Using `{{ .Release.Name }}-{{ .Chart.Name }}` is a kind of convention that we are using in our charts. 

If we are changing it we should change it for all our charts at the same time, but it could break eventually for people writing automation based on the pod names.

**Pull request closed without merging**
