### PR TITLE
Fix DNS lookup failure error for host URLs

### PR DESCRIPTION
**Pull request by FedeBev**
- [x] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [x] README.md updated with any new values or changes
- [x] Updated template tests in `${CHART}/tests/*.py`
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml` (Seems to be not required for current tests)

This is a fix PR for #394 bug, feel free to suggest any other solution/idea.

Thanks

### CODE REVIEW

**Comment by FedeBev** [comment]
CLA has now been signed.
Sorry, what I have to do now?

**Comment by pbecotte** [comment]
I wound up fixing this like this-

https://github.com/elastic/helm-charts/pull/439#issuecomment-573964098

**Comment by FedeBev** [comment]
> I wound up fixing this like this-
> 
> [#439 (comment)](https://github.com/elastic/helm-charts/pull/439#issuecomment-573964098)

That could be a great solution!
Both solutions are valid and feasible in my opinion, maybe I cane make this options configurable through values file, what do you think?

**Comment by pbecotte** [comment]
I had an earlier PR that set this variable, you could resurrect it and trim it down to just this. Eventually I came to the conclusion that host networking was the easiest solution, but almost never the right one. That's not up to me though ;)

**Comment by jmlrt** [comment]
Hi @FedeBev, 
This was already discussed a lot, host networking can be a great addition to this chart as long as it is optional and disabled by default.
You can also find an example in @pbecotte's [Filebeat PR](https://github.com/elastic/helm-charts/pull/321) (this was disabled by default in https://github.com/elastic/helm-charts/pull/391/commits/538af31822d3bbbac93b1a270493b4818a983666).

**Comment by FedeBev** [comment]
Hi @jmlrt ,
`hostNetwork` and `dnsPolicy` options are now configurable through values.

In my opinion also @pbecotte solution is fine, but I can't see the new options in 7.6 release and in my opinion is needful.

Please, could you let me know the state on that?

Thanks

**Comment by jmlrt** [comment]
@FedeBev I created #585 to add host networking to Metricbeat while staying consistent with Filebeat.
This will be merged today or in a couple of days so I'll close your PR.

I'm sorry for making you wait so long then replacing your work due to bad timing.
I hope it won't demotivate you for contributing to this repos in the future.

**Comment by FedeBev** [comment]
Hi @jmlrt, thank's for you work.

I kept the options separate to leave maximum configuration flexibility. At the moment I can't image a situation where this is really required, so it's perfectly fine for me to keep that configuration in one option and #585 is perfect for my use case.

Don't worry for the timing,  luckily the workaround was very easy 😄

**Pull request closed without merging**
