### PR TITLE
feat: add filebeat config templating

### PR DESCRIPTION
**Pull request by emmanuelCarre**
Fix: #1436

- [X] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [ ] README.md updated with any new values or changes
- [X] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

### CODE REVIEW

**Comment by samarthd** [comment]
Thanks for your contribution @emmanuelCarre ! This feature would really be very helpful. 

Unfortunately nobody has reviewed your PR - @jmlrt can you please review this or notify someone who would be able?

**Comment by emmanuelCarre** [comment]
Rebase branch from master.
PR still relevant.

Regards.

**Comment by emmanuelCarre** [comment]
Hello,

Any status from elastic side ? Maybe @jmlrt ? I published this PR 10 months ago...

**Review by dtourde-dd — APPROVED** [review]
LGTM

**Comment by emmanuelCarre** [comment]
Elastic seems not interested by this PR. Closing.

**Pull request closed without merging**
