### PR TITLE
[metricbeat] using https to connect to elasticsearch

### PR DESCRIPTION
**Pull request by framsouza**
This PR enable metricbeat to connect into Elasticsearch via https

### CODE REVIEW

**Comment by jmlrt** [comment]
ok to test

**Comment by framsouza** [comment]
jenkins test this pipeline please

**Comment by framsouza** [comment]
jenkins test this pipeline please

**Comment by jmlrt** [comment]
ok to test

**Comment by jmlrt** [comment]
ok to test

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by framsouza** [comment]
jenkins test this pipeline please

**Comment by framsouza** [comment]
jenkins test this please

**Comment by framsouza** [comment]
ok to test

**Pull request merged**
