### PR TITLE
Point to custom service account name if provided

### PR DESCRIPTION
**Pull request by mdnfiras**
this pull request is for solving this problem: https://github.com/elastic/helm-charts/issues/1455

- [ ] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [ ] README.md updated with any new values or changes
- [ ] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

### CODE REVIEW

**Comment by ebuildy** [comment]
The code is wrong:

Before:

```
      {{- if .Values.rbac.create }}
      serviceAccountName: "{{ template "elasticsearch.uname" . }}"
      {{- else if not (eq .Values.rbac.serviceAccountName "") }}
      serviceAccountName: {{ .Values.rbac.serviceAccountName | quote }}
      {{- end }}
```

Your:

```
      {{- if .Values.rbac.create }}
      {{- if eq .Values.rbac.serviceAccountName "" }}
      serviceAccountName: "{{ template "elasticsearch.uname" . }}"
      {{- else }}
      serviceAccountName: {{ .Values.rbac.serviceAccountName | quote }}
      {{- end }}
      {{- end }}
```

You dont handle the case if ``rbac.create`` is false ?

**Comment by ebuildy** [comment]
This should be:

```
      {{- if not (eq .Values.rbac.serviceAccountName "") }}
      serviceAccountName: {{ .Values.rbac.serviceAccountName | quote }}
       {{- else if .Values.rbac.create }}
      serviceAccountName: "{{ template "elasticsearch.uname" . }}"
      {{- end }}
```

**Comment by mdnfiras** [comment]
@ebuildy 

before:
```yaml
      {{- if .Values.rbac.create }}
      serviceAccountName: "{{ template "elasticsearch.uname" . }}"
      {{- else if not (eq .Values.rbac.serviceAccountName "") }}
      serviceAccountName: {{ .Values.rbac.serviceAccountName | quote }}
      {{- end }}
```

will:
`rbac.create: false` + `rbac.serviceAccountName: ""` => ""
`rbac.create: false` + `rbac.serviceAccountName: something` => "serviceAccountName: something"
`rbac.create: true` + `rbac.serviceAccountName: ""` => "serviceAccountName: <the_chart_defined>"
`rbac.create: true` + `rbac.serviceAccountName: something` => "serviceAccountName: <the_chart_defined>"

the behavior i want to change (last line):
`rbac.create: true` + `rbac.serviceAccountName: something` => "serviceAccountName: <the_chart_defined>"
i want to change to:
`rbac.create: true` + `rbac.serviceAccountName: something` => "serviceAccountName: something"

my:
```yaml
      {{- if .Values.rbac.create }}
      {{- if eq .Values.rbac.serviceAccountName "" }}
      serviceAccountName: "{{ template "elasticsearch.uname" . }}"
      {{- else }}
      serviceAccountName: {{ .Values.rbac.serviceAccountName | quote }}
      {{- end }}
      {{- end }}
```

will:
`rbac.create: false` + `rbac.serviceAccountName: ""` => ""
`rbac.create: false` + `rbac.serviceAccountName: something` => ""
`rbac.create: true` + `rbac.serviceAccountName: ""` => "serviceAccountName: <the_chart_defined>"
`rbac.create: true` + `rbac.serviceAccountName: something` => "serviceAccountName: something"

your:
```yaml
      {{- if not (eq .Values.rbac.serviceAccountName "") }}
      serviceAccountName: {{ .Values.rbac.serviceAccountName | quote }}
       {{- else if .Values.rbac.create }}
      serviceAccountName: "{{ template "elasticsearch.uname" . }}"
      {{- end }}
```

will:
`rbac.create: false` + `rbac.serviceAccountName: ""` => ""
`rbac.create: false` + `rbac.serviceAccountName: something` => "serviceAccountName: something"
`rbac.create: true` + `rbac.serviceAccountName: ""` => "serviceAccountName: <the_chart_defined>"
`rbac.create: true` + `rbac.serviceAccountName: something` => "serviceAccountName: something"

so i think your solution is more correct as it changes only what i want to change, and nothing else.

thanks!

**Review by ebuildy — APPROVED** [review]

**Review by ebuildy — APPROVED** [review]

**Comment by mdnfiras** [comment]
CI still needs an approving review.

**Comment by mdnfiras** [comment]
@ebuildy moving this to https://github.com/elastic/helm-charts/pull/1497 in order to merge to `7.16.0`

**Pull request closed without merging**
