### PR TITLE
[elasticsearch] add value to disable service

### PR DESCRIPTION
**Pull request by nflaig**
Hey guys,

right now it is not possible to completely disable the service but it is not required if the helm chart is deployed to a cluster with a service mesh (consul, istio, etc.).

Since the `service.enabled` does not apply to the headless service a different name could be considered but I think the issue rather is that both services use the same `service` value rather than `service` and `serviceHeadless`.

Fix https://github.com/elastic/helm-charts/issues/998

- [x] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [x] README.md updated with any new values or changes
- [x] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

### CODE REVIEW

**Review by jmlrt — DISMISSED** [review]
LGTM⛴

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by jmlrt** [comment]
will need to be rebased after https://github.com/elastic/helm-charts/pull/1141 merge to fix tests

**Comment by nflaig** [comment]
@jmlrt Thanks for the review! I added the new value to the README and will rebase the branch if required

**Comment by jmlrt** [comment]
jenkins test this please

**Review by jmlrt — COMMENTED** [review]
Hi @nflaig, I rebased your branch on master and fixed the conflicts.
The change LGTM to me.

Adding a test in https://github.com/elastic/helm-charts/blob/master/elasticsearch/tests/elasticsearch_test.py to ensure that the service isn't created when setting `service.enabled=false` would be great.

Are you interested in adding this test? Otherwise I think we can merge if tests are successful.

**Comment by nflaig** [comment]
@jmlrt Thanks for rebasing the branch. I added a test to check if disabling the service works as expected if `service.enabled` is set to `false`. Also I noticed that the commit message was somehow overwritten I updated the commit to have the original message, I hope thats fine

**Comment by jmlrt** [comment]
> Thanks for rebasing the branch. I added a test to check if disabling the service works as expected if `service.enabled` is set to `false`. 

👍🏻 

>Also I noticed that the commit message was somehow overwritten I updated the commit to have the original message, I hope thats fine

Yes, sorry I messed it a bit while rebasing...

**Comment by jmlrt** [comment]
jenkins test this please

**Pull request merged**
