### PR TITLE
[Issue #267] Support fullnameOverride in kibana, filebeat, metricbeat…

### PR DESCRIPTION
**Pull request by tusciucalecs**
… charts

- [x] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [x] README.md updated with any new values or changes
- [x] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

### CODE REVIEW

**Comment by tusciucalecs** [comment]
#267

**Comment by dmccaffery** [comment]
Please accept this PR. The `values.yaml` included in the chart actually has a `fullnameOverride` and `nameOverride` value indicating that the chart wants to support this but alas, the template helpers ignore the value. :feelsgood:

**Comment by jmlrt** [comment]
@tusciucalecs, thanks for the PR, can you rebase it on master to resolve conflicts?

**Comment by tusciucalecs** [comment]
@jmlrt Done.

**Comment by jmlrt** [comment]
jenkins test this please

**Pull request merged**
