### PR TITLE
[filebeat] Make chart compatible with Kubernetes-on-Windows

### LINKED ISSUE #1050: Make filebeat chart kubernetes-on-windows compatible
**Describe the feature:**

Although filebeat itself works perfectly fine on Windows and Kubernetes on Windows the Helm chart is not configurable enough to use it for both Linux and Windows.

There's 2 notable things that need to be possible:

1. Volume `varlibdockercontainers` needs to have _hostPath_ `/ProgramData/docker/containers` to be able to find the container logs. It can still be mapped to _mountPath_ `/var/lib/docker/containers`, which is actually preferable, because you can then reuse the same config between linux and windows deamonsets.
2. Mounting files with `subPath` is not possible for Windows containers, only directories can be mounted. For that reason filebeat-config and data volumes need to be mounted in different locations, without the `subPath` properties getting used.

**Describe a specific use case for the feature:**

Shipping logs from Kubernetes on Windows nodes.

### PR DESCRIPTION
**Pull request by JorritSalverda**
- [x] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [x] README.md updated with any new values or changes
- [x] Updated template tests in `${CHART}/tests/*.py` 
- [x] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

Fix #1050

### CODE REVIEW

**Comment by JorritSalverda** [comment]
Fixes #1050

**Comment by JorritSalverda** [comment]
I'm curious about why the subPath was used for the config mounts, since you can actually mount a configmap to /usr/share/filebeat and another directory to nested mount /usr/share/filebeat/data. But perhaps this didn't work in older versions of Kubernetes?

If it's needed I can add a toggle value in order to support both behaviours.

**Comment by JorritSalverda** [comment]
@jmlrt does this automatically show up for someone with Elastic? Not sure if anyone's noticing. Thx.

**Comment by JorritSalverda** [comment]
Hey @jmlrt can you please take a look at this PR and let me know if you want any changes? :)

**Comment by jmlrt** [comment]
Hi @JorritSalverda,
Thanks for opening this PR.
We'll try to review it soon. Please be patient.

**Comment by jmlrt** [comment]
Could help for https://github.com/elastic/helm-charts/issues/404

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by JorritSalverda** [comment]
Thanks, I'll have a look at the test errors!

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by JorritSalverda** [comment]
Not sure whether the failures in https://devops-ci.elastic.co/job/elastic+helm-charts+pull-request/1212/ have anything to do with the changes in this PR. The integration-filebeat job shows a lot of messages like `‘devops-ci-immutable-ubuntu-1804-1614172431721709433’ is offline`.

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by jmlrt** [comment]
Tests are still failing in https://devops-ci.elastic.co/job/elastic+helm-charts+pull-request+integration-filebeat/860/FILEBEAT_SUITE=default,KUBERNETES_VERSION=1.15,label=docker&&virtual/console

```
14:14:11 helm upgrade --wait --timeout=900s --install helm-filebeat-default ../../
14:14:11 Release "helm-filebeat-default" does not exist. Installing it now.
14:29:12 Error: timed out waiting for the condition
```

This is usually because pods aren't reaching `ready` state during Helm install.

This will require some manual tests to understand why it's failing.
In addition our CI tests are only testing K8S/Linux using GKE for now, we'll also need to do manual tests on K8S/Windows.

**Comment by JorritSalverda** [comment]
I'll have a go at testing it locally, but given that not only filebeat, but also kibana, metricbeat, logstash and apm-server integration tests are failing it might be something in a shared piece of test setup.

**Comment by jmlrt** [comment]
> I'll have a go at testing it locally, but given that not only filebeat, but also kibana, metricbeat, logstash and apm-server integration tests are failing it might be something in a shared piece of test setup.

The other products are transient error where only one test is failing while other are successful:
- https://devops-ci.elastic.co/job/elastic+helm-charts+pull-request+integration-elasticsearch/895/
- https://devops-ci.elastic.co/job/elastic+helm-charts+pull-request+integration-kibana/860/
- https://devops-ci.elastic.co/job/elastic+helm-charts+pull-request+integration-metricbeat/861/
- https://devops-ci.elastic.co/job/elastic+helm-charts+pull-request+integration-logstash/703/
- https://devops-ci.elastic.co/job/elastic+helm-charts+pull-request+integration-apm-server/627/

This is something that we need to improve but not unusual regarding that our tests are deploying 91 charts in //.

However, for Filebeat every tests are failing except `deployment` tests which aren't deploying DaemonSet and so aren't impacted by this PR:
- https://devops-ci.elastic.co/job/elastic+helm-charts+pull-request+integration-filebeat/860/

I don't have time to investigate currently but will try to take a quick look next week or the week after if needed.

**Comment by JorritSalverda** [comment]
It turned out that mounting the full configmap to the `/usr/share/filebeat` directory overwrote other files in that folder, including the filebeat binary which led to a container failing to start.

Unfortunately the previous `subPath` mounts do not work in Windows containers, so now I've added value `mountConfigWithSubpath` - defaulting to `true` - in order to use `subPath` mounts by default but allowing it to be disabled and mount a full directory instead. In order to put config in a different place for windows containers I've also made the `configMountPath` configurable and the `args` to be passed to the container, so argument `- "c:\configpath\configfile.yaml"` can be added to locate the configfile where it's actually mounted.

This now installs fine locally, but we'll have to check if all tests succeed. I did revert them to test the `subPath` behaviour.

**Pull request closed without merging**
