### PR TITLE
Fix template name

### LINKED ISSUE #478: Render error in elastic apm server helm chart
**Chart version:** 7.6.0

**Kubernetes version:** 1.14.4

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)

**Helm Version:** 2.13.0

**Describe the bug:** Got the following error during installation process:

```
Error: UPGRADE FAILED: render error in "apm-server/templates/ingress.yaml": template: apm-server/templates/ingress.yaml:2:17: executing "apm-server/templates/ingress.yaml" at <include "fullname" .>: error calling include: template: no template "fullname" associated with template "gotpl"
```

**Expected behavior:** Installation should be completed successfully

### PR DESCRIPTION
**Pull request by vhatsura**
fixes #478 

- [x] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [ ] README.md updated with any new values or changes
- [ ] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

### CODE REVIEW

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by jmlrt** [comment]
Hi @vhatsura,
Can you rebase your branch on master?

**Comment by vhatsura** [comment]
@jmlrt, done

**Comment by jmlrt** [comment]
jenkins test this please

**Pull request merged**
