### PR TITLE
Fix Mismatch Between Service Selector and Pod Labels when using Helm Aliases in Kibana

### PR DESCRIPTION
**Pull request by jamoflaw**
- [x] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [ ] README.md updated with any new values or changes
- [x] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

When using aliases to deploy Kibana twice in `requirements.yaml` ie:

```
dependencies:
  - name: kibana
    repository: "@elastic"
    version: 7.6.0
  - name: kibana
    repository: "@elastic"
    version: 7.6.0
    alias: kibana-2
```

Both instances of Kibana will deploy successfully, however the aliased version will be inaccessible as the selector on the service is configured to use the `{{ .Chart.name }}` value which in the case of the aliased chart is different.

This PR allows Kibana to be deployed with an alias in the requirements.yaml

I have added a test which proves this is a noop when deploying in its default state (ie without alias).

### CODE REVIEW

**Comment by jamoflaw** [comment]
Just to add I've been using this branch to test and push a version of Kibana which uses this alias and it works well

Am I missing anything from the PR? CLA is signed

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by jamoflaw** [comment]
I've updated the tests fixing the lint issues - running the lint-python target now returns no issues

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by jamoflaw** [comment]
Is the fail a bug in Jenkins? I can't quite see what has failed there, looks as though GKE is complaining about an older version of K8s?

**Comment by jmlrt** [comment]
It seems that GKE has dropped support of 1.13 so we need to drop tests on this version.
You'll need to rebase on master when #533 will be merged.

**Comment by jamoflaw** [comment]
OK pulled in the master branch :+1:

**Comment by jmlrt** [comment]
jenkins test this please

**Pull request merged**
