### PR TITLE
split some of the deployment and daemonset config to make things more…

### PR DESCRIPTION
**Pull request by pbecotte**
… flexible

- [x] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [x] README.md updated with any new values or changes
- [x] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`

Looking at #446 realized we may want to split daemonset/deployment config in some places. This is kind of a big change to the values file though, so not sure if theres a better way to transition. Consider this as a proposal :)

### CODE REVIEW

**Comment by FedeBev** [comment]
I agree with you: this is a big change. However I can't a better way to do that.

Thanks

**Comment by jmlrt** [comment]
jenkins test this please

**Comment by mitchellmaler** [comment]
Can this PR be merged in? We are still having issues with the resources being the same on all pods even though the daemonset pods use much less compared to the deployment pod.

**Comment by jmlrt** [comment]
Hey @pbecotte,
Thanks for your PR, however, this is a breaking change and we'd like to ensure user with old values can still use the chart after splitting config, so I started a rework in #572, which should allow re-using old values if they are still used.

**Comment by jmlrt** [comment]
Closed by #572 
Thanks for your work @pbecotte

**Pull request closed without merging**
