### PR TITLE
[metricbeat] Support secrets

### LINKED ISSUE #777: Support creating k8s helm secrets for metricbeat helm chart
**Describe the feature:**
Similar to #705 it would be nice to have this in the metricbeat chart as well. Then we can put in the certificate to elasticsearch there, as was done in https://github.com/helm/charts/blob/master/stable/metricbeat/templates/secret.yaml.

### PR DESCRIPTION
**Pull request by erihanse**
- [x] Chart version *not* bumped (the versions are all bumped and released at the same time)
- [x] README.md updated with any new values or changes
- [x] Updated template tests in `${CHART}/tests/*.py` 
- [ ] Updated integration tests in `${CHART}/examples/*/test/goss.yaml`
closes #777 

Here's an initial attempt to adding secrets to the metricbeat chart, I hope the PR is welcome. I looked at what was done in #712, and copied and adjusted the template for metricbeat accordingly. Was unsure whether or not to add tests, since similar tests are covered in the logstash chart.

### CODE REVIEW

**Comment by erihanse** [comment]
@fatmcgav sorry to bother you directly. Will this PR be reviewed any time soon?

**Comment by fatmcgav** [comment]
Jenkins test this please

**Comment by erihanse** [comment]
Is there anything missing here?

**Comment by blurpy** [comment]
I would really like to see this PR merged so we can start using this chart. How do we get hold of someone who can verify?

**Comment by fatmcgav** [comment]
Sorry for the radio silence here. 

@erihanse This is looking good. Would you be able to add a new test to exercise creating a secret?
Something like https://github.com/erihanse/helm-charts/blob/b6f54a621a0797e58ab047f4f6014d3d7c4162fa/metricbeat/tests/metricbeat_test.py#L1152-L1173 should do the job...

**Comment by erihanse** [comment]
@fatmcgav would it make sense to copy the secret-related tests from the logstash chart (#712) and make necessary adjustments? The template is the same.

**Comment by fatmcgav** [comment]
@erihanse sounds like an awesome idea!

**Comment by erihanse** [comment]
@fatmcgav it's ready for review again. I rebased on master, therefore the force-push. I copied the tests, the only change I made was to remove the assert of secretschecksum in the test method `test_adding_a_secret`.

**Comment by fatmcgav** [comment]
Cool, thanks for that @erihanse 

Jenkins test this please

**Review by fatmcgav — APPROVED** [review]
LGTM

**Comment by fatmcgav** [comment]
This has been back-ported to the relevant branches, and will be included in the next 7.9 minor release.

Thanks again for the contribution @erihanse

**Pull request merged**
